import { buildVisits,type TMAnalyticsEvent,type TMVisit } from './tm-analytics.ts';
import type { LearningAggregate } from './ads-learning-engine.ts';
import type { ProductEconomics } from './product-economics.ts';
import { calculateContributionProfit } from './profit-engine-v2.ts';

export type AttributionConfidence='EXACT'|'PROBABLE'|'UNATTRIBUTED';
export type CustomerJourney={sessionId:string;visitorId:string;startedAt:string;device:string;source:string;landingPage:string;campaign:{name:string;campaignId:string;adGroupId:string;adId:string;assetId:string;assetGroupId:string;keywordId:string;productId:string;gclid:string;term:string};confidence:AttributionConfidence;confidenceReason:string;order:{completed:boolean;number:string;value:number;items:Array<{productId:string;quantity:number}>};profit:ReturnType<typeof calculateContributionProfit>;steps:Array<{at:string;type:string;label:string;path:string;value:number}>};
function text(v:unknown){return String(v??'').trim()}
function items(visit:TMVisit){const order=[...visit.events].reverse().find(e=>e.type==='order_complete');const encoded=text(order?.meta?.item_ids);if(encoded)return encoded.split('|').slice(0,50).map(x=>{const [id,q]=x.split(':');return{productId:text(id),quantity:Math.max(1,Number(q)||1)}}).filter(x=>x.productId);const id=text(order?.meta?.item_id)||visit.campaign.productId||visit.products[0]||'';return id?[{productId:id,quantity:1}]:[]}
function confidence(v:TMVisit):[AttributionConfidence,string]{if(v.orderCompleted&&v.campaign.gclid)return['EXACT','Objednávka je v rovnakej first-party session ako zachytený GCLID.'];if(v.orderCompleted&&(v.campaign.campaignId||/cpc|ppc|paid/i.test(v.campaign.medium)))return['PROBABLE','Platená session a objednávka sú spojené, ale chýba GCLID.'];return['UNATTRIBUTED',v.orderCompleted?'Objednávka nemá spoľahlivý platený identifikátor.':'Session nemá dokončenú objednávku.']}
function label(e:TMAnalyticsEvent){if(e.type==='pageview')return`Stránka ${e.path}`;if(e.type==='add_to_cart')return`Košík: ${e.product||text(e.meta?.item_id)||'produkt'}`;if(e.type==='checkout_start')return'Začatá pokladňa';if(e.type==='shipping_select')return`Doprava: ${text(e.meta?.label)}`;if(e.type==='payment_select')return`Platba: ${text(e.meta?.label)}`;if(e.type==='order_complete')return`Objednávka ${text(e.meta?.order_number)}`;if(e.type==='search')return`Hľadanie: ${e.search||''}`;return e.type}
export function attributionEngineV3(events:TMAnalyticsEvent[],learning:LearningAggregate[],economics:ProductEconomics[],options:{vatRate?:number;variableCostEur?:number}={}):CustomerJourney[]{const econ=new Map<string,ProductEconomics>();for(const e of economics){for(const id of [e.product_id,e.woo_id,e.sku,e.merchant_id].filter(Boolean))econ.set(String(id),e)}const learned=new Map<string,LearningAggregate>();for(const a of learning)learned.set(String(a.productId),a);return buildVisits(events).filter(v=>!v.owner).map(v=>{const orderItems=items(v),ids=orderItems.map(x=>x.productId),metrics=ids.map(id=>learned.get(id)).filter(Boolean) as LearningAggregate[],totalClicks=metrics.reduce((s,x)=>s+x.clicks,0),cost=metrics.reduce((s,x)=>s+x.costEur,0),orders=metrics.reduce((s,x)=>s+x.purchases,0),allocatedCost=orders&&v.orderCompleted?cost/orders:totalClicks&&v.campaign.gclid?cost/totalClicks:0,cvr=totalClicks?orders/totalClicks:0,[level,reason]=confidence(v),profit=calculateContributionProfit({revenueWithVat:v.orderValue,adCostEur:allocatedCost,items:orderItems,economics:econ,vatRate:options.vatRate,variableCostEur:options.variableCostEur,clickToOrderRate:cvr});return{sessionId:v.sessionId,visitorId:v.visitorId,startedAt:v.startedAt,device:v.device,source:v.source,landingPage:v.landingPage,campaign:{name:v.campaign.campaign,campaignId:v.campaign.campaignId,adGroupId:v.campaign.adGroupId,adId:v.campaign.adId,assetId:v.campaign.assetId,assetGroupId:v.campaign.assetGroupId,keywordId:v.campaign.keywordId,productId:v.campaign.productId,gclid:v.campaign.gclid,term:v.campaign.term},confidence:level,confidenceReason:reason,order:{completed:v.orderCompleted,number:v.orderNumber,value:v.orderValue,items:orderItems},profit,steps:v.events.filter(e=>['pageview','search','add_to_cart','remove_from_cart','checkout_start','shipping_select','payment_select','order_complete'].includes(e.type)).map(e=>({at:e.ts,type:e.type,label:label(e),path:e.path,value:Number(e.value||0)}))}}).sort((a,b)=>Date.parse(b.startedAt)-Date.parse(a.startedAt))}
export function attributionSummary(journeys:CustomerJourney[]){const paid=journeys.filter(j=>j.campaign.gclid||j.campaign.campaignId),orders=journeys.filter(j=>j.order.completed),exact=orders.filter(j=>j.confidence==='EXACT'),probable=orders.filter(j=>j.confidence==='PROBABLE'),unattributed=orders.filter(j=>j.confidence==='UNATTRIBUTED');return{sessions:journeys.length,paidSessions:paid.length,orders:orders.length,exactOrders:exact.length,probableOrders:probable.length,unattributedOrders:unattributed.length,attributionCoverage:orders.length?(exact.length+probable.length)/orders.length:0,revenue:orders.reduce((s,j)=>s+j.order.value,0),contributionProfit:orders.reduce((s,j)=>s+j.profit.contributionProfitEur,0)}}

