import type { TmProduct } from './tm-products-cache.ts';
import { buildProductEconomics } from './product-economics.ts';
import type { MarketingCreative } from './marketing-creatives.ts';

export type CampaignBuildInput={selection:string;channel:'search'|'shopping'|'performance_max';goal:'orders'|'profit'|'new_customers'|'remarketing';dailyBudgetEur:number;creativeIds?:string[]};
const norm=(v:unknown)=>String(v??'').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]+/g,' ').trim();
const clean=(v:unknown,max:number)=>String(v??'').replace(/\s+/g,' ').trim().slice(0,max);
const unique=<T>(items:T[])=>[...new Set(items)];
const excluded=(name:string)=>/(?:\bno\s*chip\b|\bbez\s+(?:čipu|cipu|chipu)|\boem\s*(?:čip|cip|chip)|\bhatona\b)/i.test(name);
export function campaignBuilder(products:TmProduct[],creatives:MarketingCreative[],raw:CampaignBuildInput){
  const selection=clean(raw.selection,300),tokens=norm(selection).split(' ').filter(Boolean),budget=Math.max(1,Math.min(10000,Number(raw.dailyBudgetEur)||10));
  const compactSelection=norm(selection).replace(/ /g,'');
  const matched=products.filter(p=>{const hay=norm(`${p.name||''} ${p.sku||''} ${(p as any).search_text||''} ${(p.compatible_printers||[]).join(' ')}`),compactHay=hay.replace(/ /g,'');return tokens.length>0&&(tokens.every(t=>hay.includes(t))||(compactSelection.length>=4&&compactHay.includes(compactSelection)));});
  const eligible=matched.map(p=>({product:p,economics:buildProductEconomics(p)})).filter(x=>x.economics.product_type==='compatible'&&(x.economics.material_type==='toner'||x.economics.material_type==='ink')&&x.economics.stock_status==='instock'&&x.economics.selling_price>0&&x.economics.estimated_gross_margin>0&&!excluded(x.economics.name)).sort((a,b)=>b.economics.estimated_gross_margin-a.economics.estimated_gross_margin).slice(0,200);
  const selectedCreatives=creatives.filter(c=>(raw.creativeIds||[]).includes(c.id)),hasLandscape=selectedCreatives.some(c=>c.usage.includes('landscape')),hasSquare=selectedCreatives.some(c=>c.usage.includes('square'));
  const primary=eligible[0]?.economics,brand=clean(primary?.brand||products.find(p=>matched.includes(p))?.product_brand||'',30).toUpperCase(),subject=clean(selection,25),isPrinter=/\b(?:laserjet|deskjet|officejet|pixma|workforce|ecotank|mfc|dcp|hl|mf|lbp)\b/i.test(selection),intent=isPrinter?'PRINTER':'PRODUCT',offer=primary?{productId:primary.product_id,sku:primary.sku,priceEur:primary.selling_price,grossMarginEur:primary.estimated_gross_margin,valueProposition:primary.product_type==='compatible'?'Úspora oproti originálu':'Overená kvalita'}:null;
  const headlines=unique([`${subject} kompatibilné`,`${subject} skladom`,brand?`${brand} ${subject} toner`:subject,offer?.valueProposition,`Objednajte ${subject}`,`ToneryMAXIM.sk`,`Doprava zdarma od 29 €`,brand?`Náplne pre ${brand}`:'Tonery a náplne','Overený slovenský e-shop','Rýchle doručenie','17 rokov skúseností']).filter(Boolean).map(x=>clean(x,30)).filter(x=>x.length>=3);
  const descriptions=unique([`${subject} skladom. Kompatibilné náplne za výhodnú cenu s rýchlym doručením.`,`Ušetrite oproti originálu. Doprava zdarma pri objednávke od 29 €.`,`Vyberte správnu náplň ${brand?`pre ${brand}`:'pre vašu tlačiareň'} na ToneryMAXIM.sk.`,`17 rokov skúseností, slovenský e-shop a pomoc s výberom správnej náplne.`]).map(x=>clean(x,90));
  const keywords=unique([selection,`${selection} toner`,`${selection} kompatibilný`,`${selection} náplň`,...eligible.slice(0,10).map(x=>x.economics.sku)]).map(x=>clean(x,80)).filter(Boolean);
  const negatives=['zadarmo','bazoš','použitý','návod','ovládač','servis','oprava tlačiarne','tlačiareň bazár'];
  const blockers:string[]=[],warnings:string[]=[];
  if(!selection)blockers.push('Zadajte produkt, OEM kód alebo skupinu produktov.');
  if(!eligible.length)blockers.push('Nenašiel sa skladový kompatibilný produkt s kladnou maržou.');
  if(raw.channel==='performance_max'&&!hasLandscape)blockers.push('Performance Max potrebuje aspoň jeden horizontálny obrázok 1,91 : 1.');
  if(raw.channel==='performance_max'&&!hasSquare)blockers.push('Performance Max potrebuje aspoň jeden štvorcový obrázok 1 : 1.');
  if(raw.channel==='shopping'&&eligible.some(x=>!Array.isArray(x.product.images)||!x.product.images.length))warnings.push('Niektoré vybrané produkty nemajú obrázok v katalógu.');
  if(eligible.length>100)warnings.push('Výber obsahuje viac ako 100 produktov; systém použije najziskovejších 200 a odporúča rozdeliť skupinu.');
  const totalMargin=eligible.reduce((s,x)=>s+x.economics.estimated_gross_margin,0),avgMargin=eligible.length?totalMargin/eligible.length:0,coldCvr=.025,recommendedMaxCpc=Math.max(.05,Math.min(1.5,avgMargin*.4*coldCvr));
  const path=eligible.length===1?`/produkt/${encodeURIComponent(String(eligible[0].product.slug||''))}`:`/produkty?s=${encodeURIComponent(selection)}&type=compatible`;
  const productRows=eligible.map(x=>({id:x.economics.product_id,sku:x.economics.sku,name:x.economics.name,price:x.economics.selling_price,grossMargin:x.economics.estimated_gross_margin,stock:x.economics.stock_status})),assetGroups=raw.channel==='performance_max'?[{name:`${subject} | kompatibilné`,theme:selection,intent,landingPage:`https://www.tonerymaxim.sk${path}`,headlines:headlines.slice(0,15),descriptions:descriptions.slice(0,4),squareCreativeIds:selectedCreatives.filter(c=>c.usage.includes('square')).map(c=>c.id),landscapeCreativeIds:selectedCreatives.filter(c=>c.usage.includes('landscape')).map(c=>c.id),portraitCreativeIds:selectedCreatives.filter(c=>c.usage.includes('portrait')).map(c=>c.id),productIds:productRows.map(x=>x.id)}]:[];
  return{schemaVersion:2,ready:blockers.length===0,blockers,warnings,input:{...raw,selection,dailyBudgetEur:budget},strategy:{intent,offer,usp:['Doprava zdarma od 29 €','17 rokov skúseností','Overený slovenský e-shop'],landingPageReason:eligible.length===1?'Presná produktová stránka.':'Filtrovaný výpis kompatibilných produktov.'},summary:{matched:matched.length,eligible:eligible.length,averageGrossMarginEur:Number(avgMargin.toFixed(2)),recommendedMaxCpcEur:Number(recommendedMaxCpc.toFixed(2)),dailyBudgetEur:budget},structure:{campaignName:`TM | ${raw.channel.toUpperCase()} | ${selection}`,channel:raw.channel,goal:raw.goal,landingPage:`https://www.tonerymaxim.sk${path}`,headlines,descriptions,keywords,negativeKeywords:negatives,creativeIds:selectedCreatives.map(c=>c.id),assetGroups,productGroups:[{dimension:'product_id',included:productRows.map(x=>x.id),excluded:'ALL_OTHER_PRODUCTS'}]},products:productRows,limits:{headlineMax:30,descriptionMax:90,allHeadlinesValid:headlines.every(x=>x.length<=30),allDescriptionsValid:descriptions.every(x=>x.length<=90)}};
}
