import type { GoogleAdsConfig } from './google-ads-readonly.ts';
import { googleAdsValidateOperations } from './google-ads-validate-only.ts';
const clean=(v:unknown,max=255)=>String(v??'').replace(/[\u0000-\u001f\u007f]/g,' ').replace(/\s+/g,' ').trim().slice(0,max);
const micros=(v:unknown)=>Math.max(1_000_000,Math.round(Number(v||0)*1_000_000));

export function buildShoppingValidateOnlyOperations(publication:any,customerId:string,merchantId:string){if(publication?.mode!=='DRY_RUN_ONLY'||publication?.campaign?.channel!=='shopping')throw new Error('Shopping adaptér vyžaduje schválenú Shopping kampaň.');if(publication?.campaign?.status!=='PAUSED')throw new Error('Shopping kampaň musí zostať pozastavená.');const merchant=String(merchantId||'').replace(/\D/g,'');if(!/^\d{5,}$/.test(merchant))throw new Error('Chýba platné GOOGLE_MERCHANT_CENTER_ID.');if(!(publication?.products||[]).length)throw new Error('Shopping kampaň nemá produkty.');const root=`customers/${customerId}`,budget=`${root}/campaignBudgets/-11`,campaign=`${root}/campaigns/-12`,adGroup=`${root}/adGroups/-13`;return[
 {campaignBudgetOperation:{create:{resourceName:budget,name:`${clean(publication.campaign.name,180)} | rozpočet`,amountMicros:String(micros(publication.campaign.dailyBudgetEur)),deliveryMethod:'STANDARD',explicitlyShared:false}}},
 {campaignOperation:{create:{resourceName:campaign,name:clean(publication.campaign.name,180),status:'PAUSED',advertisingChannelType:'SHOPPING',campaignBudget:budget,manualCpc:{enhancedCpcEnabled:false},shoppingSetting:{merchantId:merchant,salesCountry:'SK',campaignPriority:0,enableLocal:false}}}},
 {adGroupOperation:{create:{resourceName:adGroup,name:`${clean(publication.campaign.name,180)} | produkty`,campaign,status:'PAUSED',type:'SHOPPING_PRODUCT_ADS',cpcBidMicros:String(micros(publication.campaign.recommendedMaxCpcEur))}}},
 {adGroupAdOperation:{create:{adGroup,status:'PAUSED',ad:{shoppingProductAd:{}}}}},
 {adGroupCriterionOperation:{create:{adGroup,status:'PAUSED',listingGroup:{type:'UNIT'}}}},
]}

export function performanceMaxLocalPreflight(publication:any){const blockers:string[]=[];if(publication?.mode!=='DRY_RUN_ONLY'||publication?.campaign?.channel!=='performance_max')blockers.push('Preflight vyžaduje schválenú Performance Max kampaň.');if(publication?.campaign?.status!=='PAUSED')blockers.push('Kampaň musí zostať pozastavená.');if((publication?.assets?.headlines||[]).length<3)blockers.push('Chýbajú minimálne 3 nadpisy.');if((publication?.assets?.descriptions||[]).length<2)blockers.push('Chýbajú minimálne 2 opisy.');const groups=publication?.assets?.assetGroups||[];if(!groups.length)blockers.push('PMax nemá profesionálnu asset group.');for(const g of groups){if(!(g.squareCreativeIds||[]).length)blockers.push(`Asset group ${clean(g.name)} nemá square obrázok.`);if(!(g.landscapeCreativeIds||[]).length)blockers.push(`Asset group ${clean(g.name)} nemá landscape obrázok.`);if(!(g.productIds||[]).length)blockers.push(`Asset group ${clean(g.name)} nemá produkty.`)}if(!(publication?.products||[]).length)blockers.push('PMax nemá vhodné produkty.');return{ready:blockers.length===0,blockers,mode:'LOCAL_PREFLIGHT_ONLY',campaignStatus:'PAUSED',assetCount:(publication?.assets?.creativeIds||[]).length,assetGroupCount:groups.length,productCount:(publication?.products||[]).length,requiresGoogleApiApproval:true}}

export async function googleAdsShoppingValidateOnly(config:GoogleAdsConfig,publication:any,merchantId:string,fetcher:typeof fetch=fetch){return googleAdsValidateOperations(config,buildShoppingValidateOnlyOperations(publication,config.customerId,merchantId),fetcher)}
