import type { TMVisit } from './tm-analytics.ts';
import type { LearningAggregate } from './ads-learning-engine.ts';
import type { GoogleAdsSyncStatus } from './google-ads-readonly.ts';

type MerchantSummary={eligiblePaid:number;errors:number;warnings:number;excludedChipless:number};
type Severity='critical'|'warning'|'info';
const round=(v:number,d=2)=>Number(v.toFixed(d));

export function paidFunnel(visits:TMVisit[]){const paid=visits.filter(v=>!v.owner&&(Boolean(v.campaign.gclid)||/cpc|ppc|paid/i.test(v.campaign.medium))),engaged=paid.filter(v=>v.activeMs>=30000||v.pageviews>=2),carts=paid.filter(v=>v.cartAdds>0),checkouts=paid.filter(v=>v.checkoutStarted),orders=paid.filter(v=>v.orderCompleted);const stages=[{key:'visits',label:'Návštevy',value:paid.length},{key:'engaged',label:'Aktívne návštevy',value:engaged.length},{key:'carts',label:'Košíky',value:carts.length},{key:'checkouts',label:'Pokladne',value:checkouts.length},{key:'orders',label:'Objednávky',value:orders.length}],drops=stages.slice(1).map((s,i)=>({from:stages[i].label,to:s.label,rate:stages[i].value?s.value/stages[i].value:0,loss:stages[i].value-s.value})).sort((a,b)=>a.rate-b.rate);return{stages,rates:{engagement:paid.length?engaged.length/paid.length:0,cart:paid.length?carts.length/paid.length:0,checkout:carts.length?checkouts.length/carts.length:0,purchase:checkouts.length?orders.length/checkouts.length:0,conversion:paid.length?orders.length/paid.length:0},biggestDrop:drops[0]||null}}

export function landingPageDiagnostics(visits:TMVisit[]){const map=new Map<string,any>();for(const v of visits){if(v.owner||!(v.campaign.gclid||/cpc|ppc|paid/i.test(v.campaign.medium)))continue;const path=v.landingPage||'/',x=map.get(path)||{path,visits:0,activeSeconds:0,pageviews:0,carts:0,checkouts:0,orders:0,revenue:0};x.visits++;x.activeSeconds+=Math.round(v.activeMs/1000);x.pageviews+=v.pageviews;if(v.cartAdds>0)x.carts++;if(v.checkoutStarted)x.checkouts++;if(v.orderCompleted){x.orders++;x.revenue+=Number(v.orderValue||0)}map.set(path,x)}return[...map.values()].map(x=>{const conversion=x.visits?x.orders/x.visits:0;let state='UČÍ SA',reason=`Málo dát (${x.visits}/30 návštev).`;if(x.visits>=30){if(x.orders>=2&&conversion>=.03){state='POSILNIŤ';reason='Vstupná stránka prináša objednávky s dobrým konverzným pomerom.'}else if(x.orders>0){state='PONECHAŤ';reason='Stránka konvertuje, ale potrebuje viac dát.'}else if(x.visits>=60&&x.carts===0){state='ZASTAVIŤ';reason='Veľká vzorka bez košíka; skontrolujte zhodu reklamy a stránky.'}else{state='OBMEDZIŤ';reason='Návštevy nepriniesli objednávku; stránku alebo cielenie treba upraviť.'}}return{...x,revenue:round(x.revenue),averageActiveSeconds:x.visits?Math.round(x.activeSeconds/x.visits):0,averagePages:x.visits?round(x.pageviews/x.visits,1):0,conversionRate:round(conversion,4),state,reason}}).sort((a,b)=>b.revenue-a.revenue||b.visits-a.visits)}

export function budgetGuard(learning:LearningAggregate[],dailyBudgetEur:number){const totalCost=learning.reduce((s,x)=>s+x.costEur,0),grossProfit=learning.reduce((s,x)=>s+x.grossProfitEur,0),profitAfterAds=grossProfit-totalCost,purchases=learning.reduce((s,x)=>s+x.purchases,0),confident=learning.filter(x=>x.confidence!=='LOW'),losing=learning.filter(x=>x.clicks>=50&&x.purchases===0&&x.costEur>=20),profitable=learning.filter(x=>x.purchases>=3&&x.profitAfterAdsEur>0);let action:'UČÍ SA'|'PONECHAŤ'|'POSILNIŤ'|'OBMEDZIŤ'='UČÍ SA',multiplier=1,reason='Nie je dosť dát na zmenu celkového rozpočtu.';if(confident.length>=3||purchases>=5){if(profitAfterAds>0&&profitable.length){action='POSILNIŤ';multiplier=1.15;reason='Reklamy majú kladný zisk po nákladoch; odporúča sa najviac 15 % zvýšenie.'}else if(profitAfterAds<0&&losing.length){action='OBMEDZIŤ';multiplier=.8;reason='Reklamy sú v strate a obsahujú dostatočne overené stratové produkty.'}else{action='PONECHAŤ';reason='Výkon je zmiešaný; rozpočet zatiaľ ponechajte.'}}const current=Math.max(1,Number(dailyBudgetEur)||1);return{state:action,reason,currentDailyBudgetEur:round(current),recommendedDailyBudgetEur:round(current*multiplier),maxChangePercent:action==='POSILNIŤ'?15:action==='OBMEDZIŤ'?-20:0,totalCostEur:round(totalCost),grossProfitEur:round(grossProfit),profitAfterAdsEur:round(profitAfterAds),purchases,profitableProducts:profitable.length,losingProducts:losing.length,automaticChange:false}}

export function marketingAlerts(funnel:ReturnType<typeof paidFunnel>,learning:LearningAggregate[],merchant:MerchantSummary,google:GoogleAdsSyncStatus){const alerts:Array<{severity:Severity;code:string;title:string;message:string;action:string}>=[];if(!google.configured)alerts.push({severity:'warning',code:'google_not_connected',title:'Google Ads nie je pripojený',message:'Bez API pripojenia sa nedajú načítať reálne náklady a search terms.',action:'Dokončiť API prístup po schválení Googlom.'});else if(google.error)alerts.push({severity:'critical',code:'google_error',title:'Google Ads synchronizácia zlyhala',message:google.error,action:'Skontrolovať OAuth a developer token.'});else if(!google.lastSyncAt||Date.now()-Date.parse(google.lastSyncAt)>48*3600000)alerts.push({severity:'warning',code:'google_stale',title:'Google Ads dáta sú staršie ako 48 hodín',message:'Rozhodnutia nemusia vychádzať z aktuálnych nákladov.',action:'Spustiť read-only synchronizáciu.'});if(merchant.errors>0)alerts.push({severity:'critical',code:'merchant_errors',title:`Merchant má ${merchant.errors} chýb`,message:'Produkty s chybou nemusia byť vhodné pre Shopping reklamu.',action:'Otvoriť Merchant diagnostiku a opraviť chyby.'});if(funnel.stages[0].value>=20&&funnel.stages[2].value===0)alerts.push({severity:'warning',code:'no_carts',title:'Platené návštevy nepridávajú do košíka',message:`${funnel.stages[0].value} platených návštev bez košíka.`,action:'Skontrolovať cielenie, cenu a vstupnú stránku.'});if(funnel.stages[3].value>=3&&funnel.stages[4].value===0)alerts.push({severity:'critical',code:'checkout_no_orders',title:'Pokladne bez dokončenej objednávky',message:`${funnel.stages[3].value} začatých pokladní bez objednávky.`,action:'Skontrolovať platby, dopravu a meranie purchase.'});if(Number(google.clicks||0)>=10&&funnel.stages[0].value===0)alerts.push({severity:'critical',code:'tracking_gap',title:'Google eviduje kliky, vlastná analytika nie',message:'Môže ísť o výpadok súhlasu, UTM alebo analytického skriptu.',action:'Overiť meranie pred ďalším navýšením rozpočtu.'});const losing=learning.filter(x=>x.clicks>=50&&x.purchases===0&&x.costEur>=20);if(losing.length)alerts.push({severity:'critical',code:'losing_products',title:`${losing.length} produktov míňa bez objednávky`,message:'Produkty prekročili bezpečný počet klikov aj nákladový limit.',action:'Skontrolovať návrhy ZASTAVIŤ v Ads Intelligence.'});const rank={critical:0,warning:1,info:2};return alerts.sort((a,b)=>rank[a.severity]-rank[b.severity])}

export function marketingControlCenter(visits:TMVisit[],learning:LearningAggregate[],merchant:MerchantSummary,google:GoogleAdsSyncStatus,dailyBudgetEur:number){const funnel=paidFunnel(visits),landingPages=landingPageDiagnostics(visits),budget=budgetGuard(learning,dailyBudgetEur),alerts=marketingAlerts(funnel,learning,merchant,google),todayActions=[...alerts.map(a=>({priority:a.severity==='critical'?1:2,title:a.title,detail:a.action})),...(budget.state==='POSILNIŤ'||budget.state==='OBMEDZIŤ'?[{priority:2,title:`Rozpočet: ${budget.state}`,detail:budget.reason}]:[])].sort((a,b)=>a.priority-b.priority).slice(0,20);return{generatedAt:new Date().toISOString(),budget,funnel,landingPages,alerts,todayActions,automaticChanges:false}}

