import {createHash,randomUUID} from 'node:crypto';
import {join} from 'node:path';
import {readSignedJson,writeSignedJson,TM_DATA_ROOT} from './secure-persistence.ts';
import type {CreativePerformance} from './creative-performance.ts';
import type {SearchTermDecision} from './google-ads-search-terms.ts';

export type Experiment={id:string;name:string;campaignId:string;campaignName:string;metric:'CONTRIBUTION_PROFIT'|'ORDERS'|'CART_RATE';variantA:string;variantB:string;minimumVisits:number;status:'DRAFT'|'APPROVED_NOT_PUBLISHED'|'CANCELLED';createdAt:string;approvedAt?:string;fingerprint:string};
export type OptimizationRecommendation={id:string;kind:'CREATIVE'|'SEARCH'|'LANDING_PAGE'|'BUDGET';title:string;detail:string;state:'UČÍ SA'|'PONECHAŤ'|'POSILNIŤ'|'OBMEDZIŤ'|'ZASTAVIŤ';sourceKey:string;proposedAction:string;automaticChange:false;approval:'PENDING'|'APPROVED_NOT_EXECUTED'|'REJECTED';fingerprint:string;createdAt:string;decidedAt?:string};
type Store={experiments:Experiment[];recommendations:OptimizationRecommendation[];audit:Array<{id:string;at:string;action:string;targetId:string;note?:string}>};
const FILE=join(TM_DATA_ROOT,'marketing-v2','optimization-v2.json'),clean=(v:unknown,max=300)=>String(v??'').replace(/[\u0000-\u001f\u007f]/g,' ').replace(/\s+/g,' ').trim().slice(0,max),hash=(v:unknown)=>createHash('sha256').update(JSON.stringify(v)).digest('hex');
async function readStore():Promise<Store>{return await readSignedJson<Store>(FILE)||{experiments:[],recommendations:[],audit:[]}}
async function save(s:Store){await writeSignedJson(FILE,{experiments:s.experiments.slice(0,1000),recommendations:s.recommendations.slice(0,5000),audit:s.audit.slice(-10000)})}
export async function readOptimizationV2(){return readStore()}
export async function createExperiment(raw:any){const name=clean(raw?.name,120),a=clean(raw?.variantA,100),b=clean(raw?.variantB,100);if(!name||!a||!b||a===b)throw new Error('Experiment potrebuje názov a dva rozdielne varianty.');const basis={name,campaignId:clean(raw?.campaignId,40),campaignName:clean(raw?.campaignName,180),metric:['ORDERS','CART_RATE'].includes(raw?.metric)?raw.metric:'CONTRIBUTION_PROFIT',variantA:a,variantB:b,minimumVisits:Math.max(60,Math.min(10000,Math.round(Number(raw?.minimumVisits)||100)))},item:Experiment={id:randomUUID(),...basis,status:'DRAFT',createdAt:new Date().toISOString(),fingerprint:hash(basis)},s=await readStore();s.experiments.unshift(item);s.audit.push({id:randomUUID(),at:item.createdAt,action:'experiment_created',targetId:item.id});await save(s);return item}
export async function experimentAction(id:string,action:'approve'|'cancel',confirmation?:string){const s=await readStore(),i=s.experiments.findIndex(x=>x.id===id);if(i<0)throw new Error('Experiment neexistuje.');const current=s.experiments[i];if(action==='approve'){if(current.status!=='DRAFT')throw new Error('Schváliť možno iba koncept experimentu.');if(confirmation!==`EXPERIMENT: ${current.name}`)throw new Error('Potvrdenie experimentu nie je presné.');s.experiments[i]={...current,status:'APPROVED_NOT_PUBLISHED',approvedAt:new Date().toISOString()}}else{if(current.status==='CANCELLED')return current;s.experiments[i]={...current,status:'CANCELLED'}}const at=new Date().toISOString();s.audit.push({id:randomUUID(),at,action:action==='approve'?'experiment_approved_not_published':'experiment_cancelled',targetId:id});await save(s);return s.experiments[i]}
function rec(kind:OptimizationRecommendation['kind'],sourceKey:string,title:string,detail:string,state:OptimizationRecommendation['state'],proposedAction:string):OptimizationRecommendation{const basis={kind,sourceKey,title,detail,state,proposedAction},fingerprint=hash(basis);return{id:fingerprint.slice(0,24),...basis,automaticChange:false,approval:'PENDING',fingerprint,createdAt:new Date().toISOString()}}
export function buildOptimizationRecommendations(creatives:CreativePerformance[],search:SearchTermDecision[],budget?:{state:string;reason:string;recommendedDailyBudgetEur:number}){const out:OptimizationRecommendation[]=[];for(const c of creatives){if(c.state==='POSILNIŤ')out.push(rec('CREATIVE',`${c.campaign}|${c.content}`,`Posilniť kreatívu ${c.content}`,c.reason,'POSILNIŤ','Pripraviť vyšší podiel zobrazení v novom schválenom experimente.'));if(c.state==='ZASTAVIŤ')out.push(rec('CREATIVE',`${c.campaign}|${c.content}`,`Obmedziť kreatívu ${c.content}`,c.reason,'ZASTAVIŤ','Navrhnúť pozastavenie variantu až po ručnom schválení.'))}for(const d of search){if(d.recommendedAction==='NEW_EXACT_KEYWORD')out.push(rec('SEARCH',`${d.campaignId}|${d.adGroupId}|${d.term}`,`Nové exact keyword: ${d.term}`,d.reason,'POSILNIŤ','Pridať exact keyword do návrhu kampane.'));if(d.recommendedAction==='NEGATIVE_EXACT_REVIEW')out.push(rec('SEARCH',`${d.campaignId}|${d.adGroupId}|${d.term}`,`Skontrolovať negatívne: ${d.term}`,d.reason,'ZASTAVIŤ','Pripraviť exact negatívne slovo na samostatné schválenie.'));if(d.recommendedAction==='NEW_LANDING_PAGE_REVIEW')out.push(rec('LANDING_PAGE',`${d.campaignId}|${d.term}`,`Nová landing page pre ${d.term}`,d.reason,'OBMEDZIŤ',d.landingPageSuggestion||'Pripraviť presnejšiu vstupnú stránku.'))}if(budget&&(budget.state==='POSILNIŤ'||budget.state==='OBMEDZIŤ'))out.push(rec('BUDGET','account-budget',`Rozpočet: ${budget.state}`,budget.reason,budget.state as any,`Navrhnúť denný rozpočet ${budget.recommendedDailyBudgetEur.toFixed(2)} €.`));return out.slice(0,1000)}
export async function saveRecommendations(items:OptimizationRecommendation[]){const s=await readStore(),old=new Map(s.recommendations.map(x=>[x.fingerprint,x]));s.recommendations=items.map(x=>{const previous=old.get(x.fingerprint);return previous?{...x,id:previous.id,approval:previous.approval,createdAt:previous.createdAt,decidedAt:previous.decidedAt}:x});s.audit.push({id:randomUUID(),at:new Date().toISOString(),action:'recommendations_refreshed',targetId:'all',note:`${items.length} návrhov`});await save(s);return s.recommendations}
export async function recommendationAction(id:string,action:'approve'|'reject'){const s=await readStore(),i=s.recommendations.findIndex(x=>x.id===id);if(i<0)throw new Error('Odporúčanie neexistuje.');s.recommendations[i]={...s.recommendations[i],approval:action==='approve'?'APPROVED_NOT_EXECUTED':'REJECTED',decidedAt:new Date().toISOString(),automaticChange:false};s.audit.push({id:randomUUID(),at:new Date().toISOString(),action:action==='approve'?'recommendation_approved_not_executed':'recommendation_rejected',targetId:id});await save(s);return s.recommendations[i]}

