import {join} from 'node:path';
import {readSignedJson,writeSignedJson,TM_DATA_ROOT} from './secure-persistence.ts';
export type MerchantConfig={accountId:string;clientId:string;clientSecret:string;refreshToken:string};
export type MerchantProductIssue={productId:string;offerId:string;title:string;severity:'DISAPPROVED'|'LIMITED'|'WARNING';code:string;description:string;documentationUri:string;googlePriceEur:number|null};
export type MerchantSnapshot={configured:boolean;accountId?:string;syncedAt?:string;approved:number;pending:number;disapproved:number;limited:number;products:number;issues:MerchantProductIssue[];accountIssues:any[];error?:string};
const FILE=join(TM_DATA_ROOT,'ads-intelligence','merchant-api-status.json');
const val=(s:any,n:string)=>String(s?.[n]??process.env[n]??(import.meta.env as any)?.[n]??'').trim();
export function loadMerchantConfig(source:any={}):MerchantConfig|null{const accountId=val(source,'GOOGLE_MERCHANT_CENTER_ID').replace(/\D/g,''),clientId=val(source,'GOOGLE_MERCHANT_CLIENT_ID')||val(source,'GOOGLE_ADS_CLIENT_ID'),clientSecret=val(source,'GOOGLE_MERCHANT_CLIENT_SECRET')||val(source,'GOOGLE_ADS_CLIENT_SECRET'),refreshToken=val(source,'GOOGLE_MERCHANT_REFRESH_TOKEN')||val(source,'GOOGLE_ADS_REFRESH_TOKEN');return accountId&&clientId&&clientSecret&&refreshToken?{accountId,clientId,clientSecret,refreshToken}:null}
async function token(c:MerchantConfig,fetcher:typeof fetch){const r=await fetcher('https://oauth2.googleapis.com/token',{method:'POST',headers:{'content-type':'application/x-www-form-urlencoded'},body:new URLSearchParams({grant_type:'refresh_token',client_id:c.clientId,client_secret:c.clientSecret,refresh_token:c.refreshToken}),signal:AbortSignal.timeout(15000)}),j:any=await r.json().catch(()=>({}));if(!r.ok||!j.access_token)throw new Error(`Merchant OAuth zlyhal (${r.status}): ${j.error_description||j.error||'bez access tokenu'}`);return String(j.access_token)}
async function pages(url:string,key:string,access:string,fetcher:typeof fetch,max=100){const out:any[]=[];let next='',count=0;do{if(++count>max)throw new Error('Merchant API prekročilo bezpečný limit strán.');const u=new URL(url);if(next)u.searchParams.set('pageToken',next);const r=await fetcher(u,{headers:{authorization:`Bearer ${access}`},signal:AbortSignal.timeout(30000)}),j:any=await r.json().catch(()=>({}));if(!r.ok)throw new Error(`Merchant API zlyhalo (${r.status}): ${j?.error?.message||'neznáma chyba'}`);out.push(...(Array.isArray(j[key])?j[key]:[]));next=String(j.nextPageToken||'')}while(next);return out}
function offerId(p:any){return String(p?.offerId||p?.productAttributes?.offerId||p?.name||'').split('/').pop()?.split('~').pop()||''}
function productIssues(p:any):MerchantProductIssue[]{const id=offerId(p),status=p?.productStatus||{},raw=[...(Array.isArray(status.itemLevelIssues)?status.itemLevelIssues:[]),...(Array.isArray(p?.itemLevelIssues)?p.itemLevelIssues:[])],price=Number(p?.productAttributes?.price?.amountMicros||0)/1_000_000;return raw.map((x:any)=>{const rawSeverity=String(x.severity||x.resolution||'').toUpperCase(),severity:MerchantProductIssue['severity']=/DISAPPROV|ERROR/.test(rawSeverity)?'DISAPPROVED':/LIMIT|PENDING/.test(rawSeverity)?'LIMITED':'WARNING';return{productId:String(p?.name||id),offerId:id,title:String(x.title||x.description||x.code||'Merchant problém'),severity,code:String(x.code||x.issueType||'unknown'),description:String(x.description||x.detail||''),documentationUri:String(x.documentationUri||x.documentation||''),googlePriceEur:price>0?price:null}})}
export function normalizeMerchantSnapshot(accountId:string,products:any[],aggregates:any[],accountIssues:any[]):MerchantSnapshot{const issues=products.flatMap(productIssues),stats=aggregates.reduce((a:any,x:any)=>{const s=x.statistics||{};a.approved+=Number(s.approvedCount||0);a.pending+=Number(s.pendingCount||0);a.disapproved+=Number(s.disapprovedCount||0);return a},{approved:0,pending:0,disapproved:0});return{configured:true,accountId,syncedAt:new Date().toISOString(),approved:stats.approved,pending:stats.pending,disapproved:stats.disapproved,limited:issues.filter(x=>x.severity==='LIMITED').length,products:products.length,issues:issues.slice(0,10000),accountIssues}}
export async function syncMerchantApi(source:any={},fetcher:typeof fetch=fetch){const c=loadMerchantConfig(source);if(!c)throw new Error('Merchant API nie je nakonfigurované. Doplňte GOOGLE_MERCHANT_CENTER_ID a OAuth údaje.');try{const access=await token(c,fetcher),parent=`accounts/${c.accountId}`;const [products,aggregates,accountIssues]=await Promise.all([pages(`https://merchantapi.googleapis.com/products/v1/${parent}/products?pageSize=1000`,'products',access,fetcher),pages(`https://merchantapi.googleapis.com/issueresolution/v1/${parent}/aggregateProductStatuses?pageSize=250&filter=${encodeURIComponent('reportingContext = "SHOPPING_ADS" AND country = "SK"')}`,'aggregateProductStatuses',access,fetcher),pages(`https://merchantapi.googleapis.com/accounts/v1/${parent}/issues?pageSize=100&languageCode=sk`,'accountIssues',access,fetcher)]),snapshot=normalizeMerchantSnapshot(c.accountId,products,aggregates,accountIssues);await writeSignedJson(FILE,snapshot);return snapshot}catch(e:any){const snapshot:MerchantSnapshot={configured:true,accountId:c.accountId,approved:0,pending:0,disapproved:0,limited:0,products:0,issues:[],accountIssues:[],syncedAt:new Date().toISOString(),error:e?.message||String(e)};await writeSignedJson(FILE,snapshot).catch(()=>{});throw e}}
export async function readMerchantSnapshot(source:any={}):Promise<MerchantSnapshot>{const c=loadMerchantConfig(source),saved=await readSignedJson<MerchantSnapshot>(FILE);return{configured:Boolean(c),approved:0,pending:0,disapproved:0,limited:0,products:0,issues:[],accountIssues:[],...(saved||{}),accountId:c?.accountId||saved?.accountId}}
