import { createHash,randomUUID } from 'node:crypto';
import { join } from 'node:path';
import type { TmProduct } from './tm-products-cache.ts';
import type { SearchTermDecision } from './google-ads-search-terms.ts';
import { readSignedJson,writeSignedJson,TM_DATA_ROOT } from './secure-persistence.ts';

export type SearchTermAction={id:string;key:string;decisionFingerprint:string;term:string;campaign:string;adGroup:string;action:'approved_negative'|'keep';matchType:'EXACT'|null;at:string;note?:string};
export type SearchTermActionAudit={id:string;key:string;action:'approved_negative'|'keep'|'invalidated'|'exported';at:string;note?:string};
const FILE=join(TM_DATA_ROOT,'marketing-v2','search-term-actions.json');
const clean=(v:unknown,max=300)=>String(v??'').replace(/[\u0000-\u001f\u007f]/g,' ').replace(/\s+/g,' ').trim().slice(0,max);
const norm=(v:unknown)=>clean(v,500).toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]+/g,'');
export const searchTermKey=(d:Pick<SearchTermDecision,'term'|'campaign'|'campaignId'|'adGroup'|'adGroupId'>)=>createHash('sha256').update(`${clean(d.campaignId)||clean(d.campaign)}\u0000${clean(d.adGroupId)||clean(d.adGroup)}\u0000${clean(d.term).toLowerCase()}`).digest('hex');
export const searchTermDecisionFingerprint=(d:SearchTermDecision)=>createHash('sha256').update(JSON.stringify({key:searchTermKey(d),clicks:d.clicks,costEur:d.costEur,conversions:d.conversions,state:d.state,suggestNegative:d.suggestNegative})).digest('hex');
async function readStore(){return await readSignedJson<{actions:SearchTermAction[];audit:SearchTermActionAudit[]}>(FILE)||{actions:[],audit:[]}}
async function saveStore(s:{actions:SearchTermAction[];audit:SearchTermActionAudit[]}){await writeSignedJson(FILE,{actions:s.actions.slice(0,5000),audit:s.audit.slice(-10000)})}
export async function readSearchTermActions(){return readStore()}

export function buildProtectedSearchCodes(products:TmProduct[]){const codes=new Map<string,string>();for(const p of products){const text=`${p.sku||''} ${p.name||''}`,found=text.match(/[A-Za-z]{1,6}[\s-]?\d{2,6}[A-Za-z]{0,3}/g)||[];for(const code of found){const c=norm(code);if(c.length>=4&&!codes.has(c))codes.set(c,clean(code,40))}}return codes}
export function protectedSearchTerm(term:string,productsOrCodes:TmProduct[]|Map<string,string>){const compact=norm(term);if(compact.includes('tonerymaxim'))return{protected:true,reason:'Vlastná značka ToneryMAXIM sa nesmie vylúčiť.'};if(compact.length<4)return{protected:false,reason:''};const codes=productsOrCodes instanceof Map?productsOrCodes:buildProtectedSearchCodes(productsOrCodes);for(const [code,label] of codes)if(compact.includes(code))return{protected:true,reason:`Výraz obsahuje katalógový/OEM kód ${label}.`};return{protected:false,reason:''}}

export async function decideSearchTermAction(decision:SearchTermDecision,products:TmProduct[],action:'approve_negative'|'keep',note?:unknown){const protection=protectedSearchTerm(decision.term,products);if(action==='approve_negative'&&protection.protected)throw new Error(protection.reason);if(action==='approve_negative'&&(!decision.suggestNegative||decision.state!=='ZASTAVIŤ'))throw new Error('Výraz zatiaľ nespĺňa bezpečné pravidlá pre negatívne slovo.');const store=await readStore(),key=searchTermKey(decision),at=new Date().toISOString(),safeNote=clean(note,300),record:SearchTermAction={id:randomUUID(),key,decisionFingerprint:searchTermDecisionFingerprint(decision),term:clean(decision.term),campaign:clean(decision.campaign,180),adGroup:clean(decision.adGroup,180),action:action==='approve_negative'?'approved_negative':'keep',matchType:action==='approve_negative'?'EXACT':null,at,...(safeNote?{note:safeNote}:{})};store.actions=[record,...store.actions.filter(x=>x.key!==key)];store.audit.push({id:randomUUID(),key,action:record.action,at,...(safeNote?{note:safeNote}:{})});await saveStore(store);return record}

export async function exportApprovedNegativeTerms(decisions:SearchTermDecision[],products:TmProduct[]){const store=await readStore(),byKey=new Map(decisions.map(d=>[searchTermKey(d),d])),codes=buildProtectedSearchCodes(products),rows:any[]=[];for(const action of store.actions.filter(x=>x.action==='approved_negative')){const d=byKey.get(action.key),protection=d?protectedSearchTerm(d.term,codes):{protected:true,reason:'Výraz už nie je v aktuálnom reporte.'};if(!d||action.decisionFingerprint!==searchTermDecisionFingerprint(d)||protection.protected||!d.suggestNegative)continue;rows.push({campaign:d.campaign,adGroup:d.adGroup,keyword:d.term,matchType:'EXACT',status:'APPROVED_NOT_PUBLISHED',costEur:d.costEur,clicks:d.clicks})}const at=new Date().toISOString();store.audit.push({id:randomUUID(),key:'export',action:'exported',at,note:`${rows.length} schválených výrazov`});await saveStore(store);const quote=(v:unknown)=>`"${String(v??'').replace(/"/g,'""')}"`,csv=[['campaign','ad_group','negative_keyword','match_type','status','clicks','cost_eur'],...rows.map(x=>[x.campaign,x.adGroup,x.keyword,x.matchType,x.status,x.clicks,x.costEur])].map(r=>r.map(quote).join(',')).join('\r\n');return{generatedAt:at,mode:'APPROVED_NOT_PUBLISHED',rows,csv}}
