import type { APIRoute } from 'astro';
import { constantTimeEqual,getAdminAccessKey } from '../../../lib/admin-access.ts';
import { campaignBuilder } from '../../../lib/campaign-builder.ts';
import { buildGoogleAdsPublication } from '../../../lib/google-ads-publication.ts';
import { campaignFingerprint,readMarketingApprovals,recordMarketingExport } from '../../../lib/marketing-approval.ts';
import { readMarketingCreatives } from '../../../lib/marketing-creatives.ts';
import { readMarketingDrafts,saveMarketingDraft } from '../../../lib/marketing-drafts.ts';
import { getProductsCache } from '../../../lib/tm-products-cache.ts';
export const prerender=false;
function allowed(request:Request,url:URL,locals:any){const expected=getAdminAccessKey(locals),supplied=request.headers.get('x-admin-key')||url.searchParams.get('key')||'';return Boolean(expected)&&constantTimeEqual(expected,supplied)}
export const POST:APIRoute=async({request,url,locals})=>{if(!allowed(request,url,locals))return Response.json({ok:false,error:'Unauthorized'},{status:401});try{const body=await request.json(),draftId=String(body?.draftId||'');let draft=(await readMarketingDrafts()).find(x=>x.id===draftId);if(!draft)return Response.json({ok:false,error:'Koncept neexistuje.'},{status:404});const approval=(await readMarketingApprovals()).approvals.find(x=>x.draftId===draftId);if(!approval||approval.workflowState!=='approved')return Response.json({ok:false,error:'Koncept nie je schválený.'},{status:409});const [cache,creatives]=await Promise.all([getProductsCache(),readMarketingCreatives()]);const plan=campaignBuilder(cache.products,creatives,{selection:draft.selection,channel:draft.channel,goal:draft.goal,dailyBudgetEur:draft.dailyBudgetEur,creativeIds:draft.creativeIds});draft=await saveMarketingDraft({...draft,plan,state:plan.ready?'ready':'draft'});if(campaignFingerprint(draft)!==approval.fingerprint)return Response.json({ok:false,error:'Kampaň alebo aktuálne produktové dáta sa od schválenia zmenili. Spustite kontrolu a schválenie znova.'},{status:409});const publication=buildGoogleAdsPublication(draft,approval,plan);if(!publication.ready)return Response.json({ok:false,error:'Publikačný preflight neprešiel.',blockers:publication.blockers},{status:409});await recordMarketingExport(draft.id,approval.fingerprint);return Response.json({ok:true,publication},{headers:{'cache-control':'no-store'}})}catch(error:any){return Response.json({ok:false,error:error?.message||'Publikačný preflight zlyhal.'},{status:400})}};
