import type { APIRoute } from 'astro';
import { constantTimeEqual,getAdminAccessKey } from '../../../lib/admin-access.ts';
import { campaignBuilder } from '../../../lib/campaign-builder.ts';
import { readMarketingCreatives } from '../../../lib/marketing-creatives.ts';
import { readMarketingDrafts,saveMarketingDraft } from '../../../lib/marketing-drafts.ts';
import { campaignFingerprint,decideMarketingDraft,readMarketingApprovals,reviewMarketingDraft } from '../../../lib/marketing-approval.ts';
import { getProductsCache } from '../../../lib/tm-products-cache.ts';
export const prerender=false;
function allowed(request:Request,url:URL,locals:any){const expected=getAdminAccessKey(locals),supplied=request.headers.get('x-admin-key')||url.searchParams.get('key')||'';return Boolean(expected)&&constantTimeEqual(expected,supplied)}
export const GET:APIRoute=async({request,url,locals})=>{if(!allowed(request,url,locals))return Response.json({ok:false,error:'Unauthorized'},{status:401});const [store,drafts]=await Promise.all([readMarketingApprovals(),readMarketingDrafts()]);const approvals=store.approvals.map(a=>{const draft=drafts.find(d=>d.id===a.draftId),currentFingerprint=draft?campaignFingerprint(draft):'';return{...a,valid:Boolean(draft)&&a.fingerprint===currentFingerprint,effectiveWorkflowState:Boolean(draft)&&a.fingerprint===currentFingerprint?a.workflowState:'review_required'}});return Response.json({ok:true,approvals,audit:store.audit.slice(-100).reverse()},{headers:{'cache-control':'no-store'}})};
export const POST:APIRoute=async({request,url,locals})=>{if(!allowed(request,url,locals))return Response.json({ok:false,error:'Unauthorized'},{status:401});try{const body=await request.json(),action=String(body?.action||''),draftId=String(body?.draftId||'');let draft=(await readMarketingDrafts()).find(x=>x.id===draftId);if(!draft)return Response.json({ok:false,error:'Koncept neexistuje.'},{status:404});if(action==='review'){const [cache,creatives]=await Promise.all([getProductsCache(),readMarketingCreatives()]);const plan=campaignBuilder(cache.products,creatives,{selection:draft.selection,channel:draft.channel,goal:draft.goal,dailyBudgetEur:draft.dailyBudgetEur,creativeIds:draft.creativeIds});draft=await saveMarketingDraft({...draft,plan,state:plan.ready?'ready':'draft'});const approval=await reviewMarketingDraft(draft);return Response.json({ok:true,draft,approval},{headers:{'cache-control':'no-store'}})}if(action==='approve'||action==='reject'){const approval=await decideMarketingDraft(draft,action,body?.note);return Response.json({ok:true,approval},{headers:{'cache-control':'no-store'}})}return Response.json({ok:false,error:'Neplatná akcia.'},{status:400})}catch(error:any){return Response.json({ok:false,error:error?.message||'Schvaľovanie zlyhalo.'},{status:400})}};
