import type { APIRoute } from 'astro';
import { constantTimeEqual,getAdminAccessKey } from '../../../lib/admin-access.ts';
import { loadAdsIntelligenceSettings } from '../../../lib/ads-intelligence-settings-store.ts';
import { loadGoogleAdsConfig } from '../../../lib/google-ads-readonly.ts';
import { readSearchTermReport,syncSearchTerms } from '../../../lib/google-ads-search-terms.ts';
import { buildProtectedSearchCodes,decideSearchTermAction,exportApprovedNegativeTerms,protectedSearchTerm,readSearchTermActions,searchTermKey } from '../../../lib/search-term-actions.ts';
import { getProductsCache } from '../../../lib/tm-products-cache.ts';
export const prerender=false;
function allowed(request:Request,url:URL,locals:any){const expected=getAdminAccessKey(locals),supplied=request.headers.get('x-admin-key')||url.searchParams.get('key')||'';return Boolean(expected)&&constantTimeEqual(expected,supplied)}
export const GET:APIRoute=async({request,url,locals})=>{if(!allowed(request,url,locals))return Response.json({ok:false,error:'Unauthorized'},{status:401});const [report,store,cache]=await Promise.all([readSearchTermReport(),readSearchTermActions(),getProductsCache()]),codes=buildProtectedSearchCodes(cache.products);const decorated=report?{...report,decisions:report.decisions.map(d=>({...d,key:searchTermKey(d),protection:protectedSearchTerm(d.term,codes)}))}:null;return Response.json({ok:true,report:decorated,actions:store.actions,audit:store.audit.slice(-100).reverse()},{headers:{'cache-control':'no-store'}})};
export const POST:APIRoute=async({request,url,locals})=>{if(!allowed(request,url,locals))return Response.json({ok:false,error:'Unauthorized'},{status:401});try{const body=await request.json().catch(()=>({})),action=String(body?.action||'');if(action==='approve_negative'||action==='keep'||action==='export'){const [report,cache]=await Promise.all([readSearchTermReport(),getProductsCache()]);if(!report)return Response.json({ok:false,error:'Najskôr načítajte Search Terms report.'},{status:409});if(action==='export'){const exported=await exportApprovedNegativeTerms(report.decisions,cache.products);return Response.json({ok:true,exported},{headers:{'cache-control':'no-store'}})}const decision=report.decisions.find(d=>searchTermKey(d)===String(body?.key||''));if(!decision)return Response.json({ok:false,error:'Výraz už nie je v aktuálnom reporte.'},{status:404});const record=await decideSearchTermAction(decision,cache.products,action as any,body?.note);return Response.json({ok:true,record},{headers:{'cache-control':'no-store'}})}const env=(locals as any)?.runtime?.env||{},config=loadGoogleAdsConfig(env);if(!config)return Response.json({ok:false,error:'Google Ads nie je kompletne nakonfigurovaný.'},{status:409});const settings=await loadAdsIntelligenceSettings(),report=await syncSearchTerms(config,settings,Math.max(1,Math.min(1000,Number(body?.targetCpaEur)||10)));return Response.json({ok:true,report,actions:(await readSearchTermActions()).actions},{headers:{'cache-control':'no-store'}})}catch(error:any){return Response.json({ok:false,error:error?.message||'Spracovanie vyhľadávaní zlyhalo.'},{status:400})}};
