import test from 'node:test';
import assert from 'node:assert/strict';
import {campaignBuilder} from '../src/lib/campaign-builder.ts';
import {classifySearchIntent,decideSearchTerms} from '../src/lib/google-ads-search-terms.ts';
import {buildOptimizationRecommendations,createExperiment,experimentAction,readOptimizationV2,recommendationAction,saveRecommendations} from '../src/lib/marketing-optimization-v2.ts';
import {GET as optimizationGet} from '../src/pages/api/admin/marketing-optimization-v2.ts';

const product:any={id:101,sku:'CRG-054H',slug:'canon-crg-054h-kompatibilny',name:'Canon CRG-054H kompatibilný toner skladom',price:36.9,stock_status:'instock',product_type_key:'compatible',product_brand:'Canon',categories:[{name:'Tonery'}],images:[{src:'x'}]};
const creative=(id:string,usage:string[]):any=>({id,name:id,mime:'image/png',bytes:100000,width:1200,height:usage.includes('landscape')?628:1200,aspectRatio:1,usage,qualityScore:100,qualityState:'VÝBORNÉ',qualityNotes:[],createdAt:new Date().toISOString()});
test('Campaign Builder V2 vytvorí produktový zámer, ponuku a profesionálnu PMax asset group',()=>{const out:any=campaignBuilder([product],[creative('square',['square']),creative('landscape',['landscape'])],{selection:'CRG-054H',channel:'performance_max',goal:'profit',dailyBudgetEur:10,creativeIds:['square','landscape']});assert.equal(out.schemaVersion,2);assert.equal(out.ready,true);assert.equal(out.strategy.intent,'PRODUCT');assert.equal(out.strategy.offer.sku,'CRG-054H');assert.ok(out.structure.headlines.some((x:string)=>/CRG-054H/i.test(x)));assert.equal(out.structure.assetGroups.length,1);assert.deepEqual(out.structure.assetGroups[0].squareCreativeIds,['square']);assert.deepEqual(out.structure.assetGroups[0].landscapeCreativeIds,['landscape']);assert.equal(out.structure.productGroups[0].excluded,'ALL_OTHER_PRODUCTS')});

test('Search Intelligence V2 rozlíši nákupný, produktový, tlačiarňový, informačný a nerelevantný zámer',()=>{assert.equal(classifySearchIntent('kúpiť CRG 054 toner'),'BUY');assert.equal(classifySearchIntent('canon crg 054h'),'PRODUCT');assert.equal(classifySearchIntent('toner pre tlačiareň Canon MF645cx'),'PRINTER');assert.equal(classifySearchIntent('ako vymeniť toner'),'INFORMATION');assert.equal(classifySearchIntent('oprava tlačiarne bazár'),'IRRELEVANT')});

test('Search Intelligence chráni relevantný produkt pred automatickým negatívnym slovom',()=>{const row=(term:string)=>({campaign:{id:'1',name:'Search'},adGroup:{id:'2',name:'Tonery'},searchTermView:{searchTerm:term},metrics:{impressions:1000,clicks:60,costMicros:40000000,conversions:0,conversionsValue:0}}),[productDecision,irrelevant]=decideSearchTerms([row('CRG 054H toner'),row('oprava tlačiarne bazár')],{minClicksBeforePause:50,pauseSpendTargetCpaMultiple:2},10);const p=[productDecision,irrelevant].find(x=>x.intent==='PRODUCT')!,i=[productDecision,irrelevant].find(x=>x.intent==='IRRELEVANT')!;assert.equal(p.suggestNegative,false);assert.equal(p.recommendedAction,'NEW_LANDING_PAGE_REVIEW');assert.equal(i.suggestNegative,true);assert.equal(i.negativeMatchType,'EXACT')});

test('optimalizačné odporúčania majú vždy automaticChange false',()=>{const recommendations=buildOptimizationRecommendations([{campaign:'Search',content:'A',visits:60,activeSeconds:10,averageActiveSeconds:1,pageviews:60,averagePages:1,cartAdds:0,checkouts:0,orders:0,revenue:0,conversionRate:0,state:'ZASTAVIŤ',reason:'slabé'}],[],{state:'OBMEDZIŤ',reason:'strata',recommendedDailyBudgetEur:24});assert.ok(recommendations.length>=2);assert.ok(recommendations.every(x=>x.automaticChange===false))});

test('experiment vyžaduje dva varianty a presné dvojité potvrdenie',async()=>{await assert.rejects(()=>createExperiment({name:'X',variantA:'same',variantB:'same'}),/rozdielne/i);const item=await createExperiment({name:'CRG test',variantA:'A',variantB:'B',minimumVisits:20});assert.equal(item.minimumVisits,60);await assert.rejects(()=>experimentAction(item.id,'approve','áno'),/presné/i);const approved=await experimentAction(item.id,'approve','EXPERIMENT: CRG test');assert.equal(approved.status,'APPROVED_NOT_PUBLISHED');assert.equal((await readOptimizationV2()).audit.some(x=>x.action==='experiment_approved_not_published'),true)});

test('schválenie odporúčania ho nikdy nevykoná',async()=>{const items=await saveRecommendations(buildOptimizationRecommendations([],[],{state:'POSILNIŤ',reason:'zisk',recommendedDailyBudgetEur:34.5}));const approved=await recommendationAction(items[0].id,'approve');assert.equal(approved.approval,'APPROVED_NOT_EXECUTED');assert.equal(approved.automaticChange,false)});

test('Optimization API odmietne anonymný prístup',async()=>{const response=await optimizationGet({request:new Request('https://www.tonerymaxim.sk/api/admin/marketing-optimization-v2'),url:new URL('https://www.tonerymaxim.sk/api/admin/marketing-optimization-v2'),locals:{runtime:{env:{TM_ANALYTICS_ADMIN_KEY:'0123456789abcdef0123456789abcdef'}}}} as any);assert.equal(response.status,401)});

